name: knn_penguins
channels:
  - defaults
  - conda-forge
dependencies:
  # Core
  - applications=3.11
  - pip

  # Data Science & Machine Learning
  - numpy>=1.26
  - pandas>=2.0
  - scikit-learn=1.5.0
  - seaborn=0.13.0
  - matplotlib

  # Testing
  - pytest

  # Optional: if you use Jupyter notebooks
  - jupyter